### ISSUE TITLE
PHP8 does not like required parameter $cache follows optional parameter $frameWalkers

### ISSUE THREAD

**Issue by gennadigennadigennadi** [phpactor/worse-reflection#102]
https://github.com/phpactor/worse-reflection/blob/faf4362c6140aeb8cfebc67c7cf96acdc984323c/lib/Core/ServiceLocator.php#L67

<img width="994" alt="Screenshot 2021-04-23 at 18 31 19" src="https://user-images.githubusercontent.com/3352744/115901973-2a65d880-a462-11eb-966a-353f20622ca3.png">

I'm just getting this deprecation after i updated phpactor. Right now I only found the ReflectorBuilder initiating the ServiceLocator, maybe just remove the optional values would fix the deprecation?

**Comment by dantleech** [comment]
yes I think that would fix it
