### ISSUE TITLE
Allow custom type inference

### ISSUE THREAD

**Issue by Slamdunk** [phpactor/worse-reflection#107]
Hi, Phpactor already provides some basic, useful type inference (see https://phpactor.readthedocs.io/en/master/reference/completion.html#type-inference) and I wonder if and how we could allow custom type inference too, some example may be:

1. PSR-11, see https://www.php-fig.org/psr/psr-11/
    ```php
    /** @var \Psr\Container\ContainerInterface $container */

    $myService = $container->get(MyService::class);
    // $myService should be inferred as `MyService`
    ```
2. Doctrine, see https://github.com/phpstan/phpstan-doctrine
    * Provides correct return type for `Doctrine\ORM\EntityManager::find`
3. Symfony, see https://github.com/phpstan/phpstan-symfony

**Comment by dantleech** [comment]
Yes this is possible via. extensions, kindof: https://github.com/phpactor/phpunit-extension/blob/master/lib/FrameWalker/AssertInstanceOfWalker.php

Note that WR system is not ideal

**Comment by Slamdunk** [comment]
I'm looking into https://github.com/phpactor/phpunit-extension/blob/master/tests/Unit/FrameWalker/AssertInstanceOfWalkerTest.php and I guess `<>` is the placeholder where the scope is evaluated at.

If so, why this case has two `<>`?

https://github.com/phpactor/phpunit-extension/blob/b28f574dd495778577f0b76b25d50b4c254c368e/tests/Unit/FrameWalker/AssertInstanceOfWalkerTest.php#L82-L86

**Comment by dantleech** [comment]
Probably a mistake, doesn't seem to be used (the utility does support 2 offsers for ranges, but that's not the case here

**Comment by Slamdunk** [comment]
Thank you
